# Generated by Django 2.2.8 on 2019-12-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gestionnaire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.Gestionnaire'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='gestionnaire',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='lab.Gestionnaire'),
        ),
    ]
