# Generated by Django 2.2.8 on 2020-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20191220_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_cnrs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cnrs',
            field=models.BooleanField(default=True),
        ),
    ]
