# Generated by Django 2.2.8 on 2020-01-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_auto_20200108_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
    ]
