# Generated by Django 2.2.8 on 2020-01-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_auto_20200108_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='pricing',
            field=models.CharField(choices=[('T1', 'Private Prices'), ('T2', 'Academic Prices'), ('T3', 'Academic international or Private'), ('T3ANR', 'Academic National')], default='T3ANR', max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_category',
            field=models.CharField(choices=[('T1', 'Private Prices'), ('T2', 'Academic Prices'), ('T3', 'Academic international or Private'), ('T3ANR', 'Academic National')], default='T3ANR', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='pricing',
            field=models.CharField(choices=[('T1', 'Private Prices'), ('T2', 'Academic Prices'), ('T3', 'Academic international or Private'), ('T3ANR', 'Academic National')], default='T3ANR', max_length=200),
        ),
    ]
