# Generated by Django 2.2.8 on 2020-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_auto_20200108_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price_entity', 'price_name']},
        ),
        migrations.RemoveField(
            model_name='price',
            name='price_category',
        ),
    ]
