# Generated by Django 2.2.8 on 2020-01-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_auto_20200108_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price_entity', 'price_name', 'price_category']},
        ),
        migrations.AddField(
            model_name='price',
            name='price_category',
            field=models.CharField(choices=[('T1', 'Private Prices'), ('T2', 'Academic Prices'), ('T3', 'Academic international or Private'), ('T3ANR', 'Academic National')], default='T3ANR', max_length=200),
        ),
    ]
