# Generated by Django 2.2.8 on 2020-01-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20200108_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_academic',
            field=models.BooleanField(default=True),
        ),
    ]
