# Generated by Django 2.2.8 on 2020-01-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20200108_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='pricing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pricing',
        ),
    ]
