# Generated by Django 2.2.8 on 2020-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20200108_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
