# Generated by Django 2.2.8 on 2019-12-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engi', '0002_auto_20191220_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='worker',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.User'),
        ),
    ]
